services:
  mongo:  # Service name
    image: mongo  # Docker image to use
    ports:
      - "27017:27017"  # Port mapping from host to container
    
  
  redis: 
    image: redis:latest
    ports:
    - "6379:6379"